### ISSUE TITLE
Commenti a Gruppo.py

### ISSUE THREAD

**Issue by iannellog** [marcosal30/Tombola#10]
Metodo **crea_gruppo**:
- manca un commento alla riga `s=np.sum(conta_colonne[:,0])`, in particolare quale è il ruolo della variabile `s`? In altre parole che informazione contiene?
- stessa osservazione per le righe `s=np.sum(conta_colonne[:,k])`,  `sr=np.sum(conta_righe,1)`, `r=np.argmin(conta_righe[t,:])`, e forse altre
- il `continue` alla fine del `for` è inutile (anche nel secondo `for`)

In generale credo di aver capito la logica dell'algoritmo, ma ho due osservazioni:
- bisognerebbe riuscire a spiegarlo in odo sintetico (quando avete completato il progetto provateci, e magari poi ne discutiamo)
- non sono sicuro che sia garantita la terminazione: andrebbe dimostrato, ma anche questo rimandiamolo a dopo, per ora mantenete pure questo algoritmo

Metodo **genera_gruppi**:
- è duplicato in Utils.py, sta meglio in questa classe (o forse in questo file come function indipendente); in ogni caso eliminarne uno dei due

Metodo ** elimina_numero**:
- sembra non utilizzato, serve?

**Comment by marcosal30** [comment]
Gentile Professore, abbiamo sostituito il metodo crea Gruppo con un codice meno contorto che svolge la stessa stessa funzione ed utilizza il metodo **elimina_numero**. Abbiamo inoltre reso genera_gruppo una function indipendente in questo stesso file e abbiamo eliminato il doppione in Utils.py
