### ISSUE TITLE
metodo crea_gruppo

### ISSUE THREAD

**Issue by iannellog** [marcosal30/Tombola#12]
L'algoritmo di generazione del gruppo non mi sembra più comprensibile del precedente.
Vorrei discuterlo in call. Non se se chiedo troppo nel fissare una call ancora per sabato mattina tra le 9.30 e le 11.30 (non fate complimenti ... ). 
Prometto che questa volta risiamo in una mezz'ora (a meno che non abbiate voi bisogno di altro).

N.B. Questa issue non è un invito a cambiare prima di averne parlato in call

**Comment by giulianosalvati** [comment]
Salve professore, 

confermiamo l'appuntamento per domattina alle 9.30.
Grazie, buona giornata.

**Comment by iannellog** [comment]
Avrei ancora una questione. 

Il metodo `swap_posizioni` dovrebbe competere la distribuzione delle posizioni dei numeri nel gruppo. In altre parole dopo questo metodo gli uni devono verificare tutti i vincoli.

La domanda è: possiamo essere sicuri che non sia rimasta qualche colonna che complessivamente ha più 1 di quanti ne deve avere? In altre parole avete un ragionamento rigoroso che lo garantisce?

Non converrebbe verificarlo con un metodo ad hoc e se non fosse così ripetere il metodo  `swap_posizioni` fino a quando tutti i vincoli non sono verificati? Tra l'altro se a un certo punto del procedimento la variabile `differenza` contiene solo zeri vuol dire che tutti i vincoli sono soddisfatti e potete terminare l'algoritmo senza guardare la cartelle successive (anche in questo caso è un'ottimizzazione poco rilevante in pratica, ma è utile per voi sviluppare sensibilità su questi aspetti perché in altri casi si possono avere guadagni rilevanti).

**Comment by marcosal30** [comment]
Gentile Professore,
abbiamo aggiunto un metodo che verifica che siano rispettati i vincoli sulle colonne. Tramite un ciclo while fino a quando questa condizione non è verificata vengono trovate nuove posizioni per creare un gruppo di cartelle corretto. Inoltre abbiamo aggiunto una condizione nel metodo swap_posizioni tramite cui, se i vincoli sono già rispettati, il ciclo può terminare prima senza controllare le altre cartelle.

**Comment by iannellog** [comment]
Ok, ma siete a mio avviso andati troppo oltre. 
Non c'è bisogno (mi sembra) di ripetere tutte l'assegnazione, ma sono il metodo `swap_posizioni`. Modificate il metodo `crea_gruppo` come segue:

        . . . 
        self.svuota_gruppo()
        self.posiziona_90()
        self.assegna_posizioni()

        while not self.controllo_vincoli_colonne(vincoli_colonne): #il ciclo termina solo quando effettivamente il gruppo rispetta i vincoli
            self.swap_posizioni(vincoli_colonne)

        self.assegna_numeri()

Così il metodo da voi ideato mi sembra originale e carino

**Comment by marcosal30** [comment]
Gentile professore,
abbiamo modificato il ciclo while come ci ha consigliato. Grazie per il riscontro e buona serata.
