### ISSUE TITLE
visualizza stato cartelle

### ISSUE THREAD

**Issue by iannellog** [marcosal30/Tombola#13]
Bisognerebbe  introdurre la possibilità di visualizzare in qualunque fare del gioco a schermo lo stato di occupazione di tutte le cartelle dei giocatori (incluso dopo aver fatto tombola).

Quando di chiede di estrarre un nuovo numero se si digita un tasto particolare prima di estrarre viene visualizzato lo stato di tutte le cartelle. 

Usando la vostra rappresentazione delle cartelle basterebbe un metodo del tipo (per un generico giocatore)

    def stampa_cartelle:
        print(f"Cartelle del giocatore {self.nome}")
        for i in range(0,len(self.cartelle)): 
            for r in range(3):
                # visualizza una riga della cartella
                print([str(self.cartelle[I][r][j]).zfill(4) for j in range(9)])
            print()  # lascia una riga tra una cartella e la successiva

**Comment by MariaElenaContini** [comment]
Buongiorno professore,
Volevo avvisarla che questa issue è stata risolta.
In attesa di un suo gentile riscontro, le auguro una buona giornata.
