### ISSUE TITLE
Commenti a Cartellone.py

### ISSUE THREAD

**Issue by iannellog** [marcosal30/Tombola#15]
Poiché avete separato i metodi `check_estrazione_cartellone` e `check_vincite_cartellone`, nel secondo siete costretti a ricontrollare tutte le righe di tutte le cartelle. In effetti solo la cartella in cui c'è il numero estratto può dar luogo a una vincita. Inoltre se mantenete un contatore per ciascuna cartella dei numeri già estratti del cartellone dovete addirittura controllare solo la riga in cui c'è il numero estratto.

Implementare questo commento non è obbligatorio, ma riflettete se con poche modifiche potete rendere l'algoritmo più efficiente (in questo caso la cosa non è rilevante in pratica perché le cartelle sono solo 6, ma capire come semplificare i cicli usando variabili ausiliarie è una tecnica che nei casi reali può cambiare drasticamente le prestazioni).

**Comment by MariaElenaContini** [comment]
Buongiorno professore,
Abbiamo implementato un miglioramento al codice per ridurre i cicli. Pur non implementando un contatore, abbiamo fatto in modo di non fare il ciclo sulle 6 cartelle ne per il check di estrazione ne per quello delle vincite.
In attesa di un suo gentile riscontro, le auguro una buona giornata.
