### ISSUE TITLE
Commenti a Utils.py

### ISSUE THREAD

**Issue by iannellog** [marcosal30/Tombola#6]
function **genera_gruppi**:
- migliorare il commento: "Metodo che crea tanti gruppi di 6 cartelle ciascuno in modo da avere un numero di cartelle complessivo maggiore o uguale al numero di cartelle richieste"
- migliorare il commento sull'output: "lista di tutte le cartelle generate (in totale sono un multiplo di 6)"

function **check_estrazione_corrente**:
- manca il commento

*Maria Elena, quando hai corretto rispondi a questa issue (anche solo scrivendo: "Fatto quanto richiesto") così ricevo un avviso e chiudo la issue*

**Comment by MariaElenaContini** [comment]
Buongiorno professore, 
Ho aggiunto/modificato come richiesto i commenti al file Utils.py.
