### ISSUE TITLE
Commenti a Banco.py

### ISSUE THREAD

**Issue by iannellog** [marcosal30/Tombola#7]
In generale: i nomi dei file o tutti con iniziale maiuscola o tutti con iniziale minuscola. All'interno di un progetto conviene usare convenzioni uniformi

metodo **assegna_cartelle**:
- migliorare come è scritta parte finale del commento iniziale (non si capisce bene)
- un commento all'inizio del ciclo for (per es.: "crea i giocatori e assegna casualmente a ciascun giocatore le cartelle richieste")

**Comment by giulianosalvati** [comment]
Salve professore,
abbiamo rinominato i file come da lei suggerito e apportato i commenti richiesti al suddetto metodo.
Buona giornata
