### ISSUE TITLE
Commenti a giocatore.py

### ISSUE THREAD

**Issue by iannellog** [marcosal30/Tombola#9]
classe **Giocatore**:
- Nel costruttore il parametro cartelle sembra inutile e di fatto non utilizzato
- Nel metodo **controllo_cartelle**: 
   - per uniformità con gli altri casi se si è fatta tombola sarebbe più logico restituire il risultato e lasciare che sia il main a terminare piuttosto  che terminare in modo improvviso
   - in generale il modo di determinare il risultato è un po' involuto, ma per ora lasciarlo così se non crea problemi

**Comment by MariaElenaContini** [comment]
Salve professore,
Per quanto riguarda il parametro cartelle, in realtà viene utilizzato in quanto raccoglie le cartelle assegnate al giocatore. Bisogna eliminarlo ugualmente?
Per quanto riguarda il controllo_cartelle, invece, ci lavoreremo.. ne stavamo proprio parlando in call con il resto del gruppo. Secondo lei come potremmo fare? Magari introdurre una variabile stringa che ci permetta di controllare cosa viene stampato e di conseguenza terminare il programma se è uguale a tombola?

**Comment by MariaElenaContini** [comment]
Salve professore, volevo avvertirla che abbiamo fatto in modo di far terminare il gioco dal main di modo da non terminarlo in modo improvviso.

**Comment by iannellog** [comment]
Per consideriamo chiusa questa issue. 
Vedi nuova issue su "Cartella"
